//go:build !ignore_autogenerated

// Code generated by hand (no controller-gen). DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// --------------------------------------------------------------------------
// NodePool
// --------------------------------------------------------------------------

// DeepCopyInto writes a deep copy of the receiver into out.
func (in *NodePool) DeepCopyInto(out *NodePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of the receiver.
func (in *NodePool) DeepCopy() *NodePool {
	if in == nil {
		return nil
	}
	out := new(NodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *NodePool) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

// --------------------------------------------------------------------------
// NodePoolList
// --------------------------------------------------------------------------

func (in *NodePoolList) DeepCopyInto(out *NodePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]NodePool, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *NodePoolList) DeepCopy() *NodePoolList {
	if in == nil {
		return nil
	}
	out := new(NodePoolList)
	in.DeepCopyInto(out)
	return out
}

func (in *NodePoolList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

// --------------------------------------------------------------------------
// NodePoolSpec
// --------------------------------------------------------------------------

func (in *NodePoolSpec) DeepCopyInto(out *NodePoolSpec) {
	*out = *in
	in.ProviderConfig.DeepCopyInto(&out.ProviderConfig)
	out.Scaling = in.Scaling
	out.Talos = in.Talos
	in.NodeTemplate.DeepCopyInto(&out.NodeTemplate)
}

func (in *NodePoolSpec) DeepCopy() *NodePoolSpec {
	if in == nil {
		return nil
	}
	out := new(NodePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// --------------------------------------------------------------------------
// ProviderConfig
// --------------------------------------------------------------------------

func (in *ProviderConfig) DeepCopyInto(out *ProviderConfig) {
	*out = *in
	if in.Labels != nil {
		out.Labels = make(map[string]string, len(in.Labels))
		for k, v := range in.Labels {
			out.Labels[k] = v
		}
	}
}

func (in *ProviderConfig) DeepCopy() *ProviderConfig {
	if in == nil {
		return nil
	}
	out := new(ProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// --------------------------------------------------------------------------
// ScalingBehavior (all value types — shallow copy is fine)
// --------------------------------------------------------------------------

func (in *ScalingBehavior) DeepCopyInto(out *ScalingBehavior) {
	*out = *in
}

func (in *ScalingBehavior) DeepCopy() *ScalingBehavior {
	if in == nil {
		return nil
	}
	out := new(ScalingBehavior)
	*out = *in
	return out
}

// --------------------------------------------------------------------------
// TalosReference (all value types)
// --------------------------------------------------------------------------

func (in *TalosReference) DeepCopyInto(out *TalosReference) {
	*out = *in
}

func (in *TalosReference) DeepCopy() *TalosReference {
	if in == nil {
		return nil
	}
	out := new(TalosReference)
	*out = *in
	return out
}

// --------------------------------------------------------------------------
// NodeTemplate
// --------------------------------------------------------------------------

func (in *NodeTemplate) DeepCopyInto(out *NodeTemplate) {
	*out = *in
	if in.Labels != nil {
		out.Labels = make(map[string]string, len(in.Labels))
		for k, v := range in.Labels {
			out.Labels[k] = v
		}
	}
	if in.Annotations != nil {
		out.Annotations = make(map[string]string, len(in.Annotations))
		for k, v := range in.Annotations {
			out.Annotations[k] = v
		}
	}
	if in.Taints != nil {
		out.Taints = make([]Taint, len(in.Taints))
		copy(out.Taints, in.Taints)
	}
}

func (in *NodeTemplate) DeepCopy() *NodeTemplate {
	if in == nil {
		return nil
	}
	out := new(NodeTemplate)
	in.DeepCopyInto(out)
	return out
}

// --------------------------------------------------------------------------
// Taint (all value types)
// --------------------------------------------------------------------------

func (in *Taint) DeepCopyInto(out *Taint) {
	*out = *in
}

func (in *Taint) DeepCopy() *Taint {
	if in == nil {
		return nil
	}
	out := new(Taint)
	*out = *in
	return out
}

// --------------------------------------------------------------------------
// NodePoolStatus
// --------------------------------------------------------------------------

func (in *NodePoolStatus) DeepCopyInto(out *NodePoolStatus) {
	*out = *in
	if in.LastScaleTime != nil {
		out.LastScaleTime = in.LastScaleTime.DeepCopy()
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *NodePoolStatus) DeepCopy() *NodePoolStatus {
	if in == nil {
		return nil
	}
	out := new(NodePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// --------------------------------------------------------------------------
// NodeClaim
// --------------------------------------------------------------------------

func (in *NodeClaim) DeepCopyInto(out *NodeClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *NodeClaim) DeepCopy() *NodeClaim {
	if in == nil {
		return nil
	}
	out := new(NodeClaim)
	in.DeepCopyInto(out)
	return out
}

func (in *NodeClaim) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

// --------------------------------------------------------------------------
// NodeClaimList
// --------------------------------------------------------------------------

func (in *NodeClaimList) DeepCopyInto(out *NodeClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]NodeClaim, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *NodeClaimList) DeepCopy() *NodeClaimList {
	if in == nil {
		return nil
	}
	out := new(NodeClaimList)
	in.DeepCopyInto(out)
	return out
}

func (in *NodeClaimList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

// --------------------------------------------------------------------------
// NodeClaimSpec
// --------------------------------------------------------------------------

func (in *NodeClaimSpec) DeepCopyInto(out *NodeClaimSpec) {
	*out = *in
	in.ProviderConfig.DeepCopyInto(&out.ProviderConfig)
	out.Talos = in.Talos
	in.NodeTemplate.DeepCopyInto(&out.NodeTemplate)
}

func (in *NodeClaimSpec) DeepCopy() *NodeClaimSpec {
	if in == nil {
		return nil
	}
	out := new(NodeClaimSpec)
	in.DeepCopyInto(out)
	return out
}

// --------------------------------------------------------------------------
// NodeClaimStatus
// --------------------------------------------------------------------------

func (in *NodeClaimStatus) DeepCopyInto(out *NodeClaimStatus) {
	*out = *in
	if in.IPs != nil {
		out.IPs = make([]string, len(in.IPs))
		copy(out.IPs, in.IPs)
	}
	if in.CreatedAt != nil {
		out.CreatedAt = in.CreatedAt.DeepCopy()
	}
	if in.ReadyAt != nil {
		out.ReadyAt = in.ReadyAt.DeepCopy()
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *NodeClaimStatus) DeepCopy() *NodeClaimStatus {
	if in == nil {
		return nil
	}
	out := new(NodeClaimStatus)
	in.DeepCopyInto(out)
	return out
}
