apiVersion: v1
kind: Secret
metadata:
  name: {{ .SecretName }}
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: konductor-operator
    app.kubernetes.io/managed-by: konductor
type: Opaque
data:
  hcloud-token: {{ .HCloudTokenBase64 }}
  talos-worker-config: {{ .TalosConfigBase64 }}
